# Pytorch 是什么

它是一个基于Python的科学计算包，有两大优势：
1. 它是Numpy的一个替代品，且能够使用GPUs来加速运算。
2. 它为深度学习研究提供极大的开发便捷和运算速度。

## Tensors

Tensor 类似于NumPy中的ndarray, 不同之处在于Tensor能够使用GPU加速运算。

In [2]:
from __future__ import print_function
import torch

一个未被初始化的矩阵在声明后，在使用这个矩阵前，不会有确定的可知的值。当一个矩阵被创建后，它的值取决于那块内存中原有的值。

创建一个未被初始化的5x3的矩阵

In [3]:
x = torch.empty(5, 3)
print(x)

tensor([[4.5918e-39, 4.2246e-39, 1.0286e-38],
        [1.0653e-38, 1.0194e-38, 8.4490e-39],
        [1.0469e-38, 9.3674e-39, 9.9184e-39],
        [8.7245e-39, 9.2755e-39, 8.9082e-39],
        [9.9184e-39, 8.4490e-39, 9.6429e-39]])


创建一个随机初始化的矩阵

In [4]:
x = torch.rand(5,3)
print(x)

tensor([[0.4194, 0.9025, 0.5925],
        [0.6665, 0.7693, 0.5266],
        [0.5249, 0.3439, 0.4748],
        [0.5014, 0.6247, 0.0783],
        [0.4185, 0.3366, 0.7197]])


创建一个类型为long的矩阵

In [7]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


由数据构建tensor

In [10]:
x = torch.tensor([5, 5, 3])
print(x)

tensor([5, 5, 3])


在已有的tensor基础上创建tensor。除非用户提供新的参数，例如dtype，否则这些方法将会重用原来tensor的属性。

In [11]:
x = x.new_ones(5, 3, dtype=torch.double)
print(x)
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.9319, -0.7855,  0.3246],
        [-0.3925,  1.4326, -0.7195],
        [ 1.7648, -1.6810,  0.2100],
        [ 1.2338,  0.1133, -2.3228],
        [-0.8139,  1.0469, -0.6805]])


查看x的size

In [12]:
print(x.size())

torch.Size([5, 3])


torch.Size 本质上是一个元组（tuple）

## 运算

这里有很多运算符。在下面的例子中，我们将去看一看这些加法的运算。

形式1

In [13]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 1.3081, -0.0859,  0.3382],
        [ 0.3161,  2.0554,  0.2192],
        [ 2.4716, -1.3871,  0.4853],
        [ 1.4612,  1.0585, -1.3668],
        [-0.6379,  1.4968, -0.3605]])


形式2

In [14]:
print(torch.add(x, y))

tensor([[ 1.3081, -0.0859,  0.3382],
        [ 0.3161,  2.0554,  0.2192],
        [ 2.4716, -1.3871,  0.4853],
        [ 1.4612,  1.0585, -1.3668],
        [-0.6379,  1.4968, -0.3605]])


提供一个输出tensor作为参数

In [15]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 1.3081, -0.0859,  0.3382],
        [ 0.3161,  2.0554,  0.2192],
        [ 2.4716, -1.3871,  0.4853],
        [ 1.4612,  1.0585, -1.3668],
        [-0.6379,  1.4968, -0.3605]])


原地操作（in-place），带_的方法都是原地操作，e.g. x.copy_(y),x.t_()都会改变x的值。

In [17]:
y.add_(x)
print(y)

tensor([[ 1.3081, -0.0859,  0.3382],
        [ 0.3161,  2.0554,  0.2192],
        [ 2.4716, -1.3871,  0.4853],
        [ 1.4612,  1.0585, -1.3668],
        [-0.6379,  1.4968, -0.3605]])


可以对tensor使用切片操作

In [19]:
print(x)
print(x[:, 1])

tensor([[ 0.9319, -0.7855,  0.3246],
        [-0.3925,  1.4326, -0.7195],
        [ 1.7648, -1.6810,  0.2100],
        [ 1.2338,  0.1133, -2.3228],
        [-0.8139,  1.0469, -0.6805]])
tensor([-0.7855,  1.4326, -1.6810,  0.1133,  1.0469])


使用torch.view来修改tensor的形状

In [20]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8) # -1表示可以推理出来
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


如果有一个单元素的tensor，可以通过.item()方法，获得一个python中的数值。

In [21]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([1.2701])
1.2701077461242676


更多tensor的运算请访问[这个链接](https://pytorch.org/docs/stable/torch.html)


## 和NumPy转换

把一个tensor转换成一个numpy array轻而易举，反之亦然。

如果tensor在cpu上，那么他和numpy array共享一块内存，改变一个就会影响另一个。

tensor TO numpy

In [22]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [23]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


验证一下，他们是否在同一块内存。

In [24]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


NumPy TO tensor

In [25]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


除了CharTensor，所有的Tensor都支持与numpy的互相转换。

## CUDA Tensor

tensor能够被移动到其他设备，例如gpu，通过.to()方法

In [29]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))

tensor([2.2701], device='cuda:0')
tensor([2.2701], dtype=torch.float64)
